config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "auth", path_names: {sign_in: "login",
    sign_out: "logout"},
    controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  namespace :admin do
    root "dogs#index"
    resources :categories
    resources :users
    resources :dogs
    resources :reviews
  end
  root "dogs#index"
  resources :users
  resources :dogs
  resources :reviews
  resources :favorites, only: [:create, :destroy, :index]
  resources :compares
  resources :events
  resources :user_events
end

app/models/dog.rb
class Dog < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :category
  belongs_to :user
  has_many :reviews, dependent: :destroy, as: :targetable
  has_many :favorites, dependent: :destroy

  validates :name, presence: true
  validates :weight, presence: true
  validates :height, presence: true
  validates :avg_life_expectancy, presence: true

  scope :search_dog, -> search_name {where "name ILIKE :search_name",
    search_name: "%#{search_name}%"}
  scope :search_weight, ->value, value_2{where "weight >= ? and weight <= ?",
    value, value_2}
  scope :search_height, ->value, value_2{where "height >= ? and height <= ?",
    value, value_2}

  class << self
    def search search_name, value, value_2
      if search_name == "name"
        search_dog value
      elsif search_name == "weight"
        search_weight value, value_2
      elsif search_name == "height"
        search_height value, value_2
      else
        all
      end
    end
  end
end

app/controllers/admin/dogs_controller.rb
class Admin::DogsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_categories, only: [:index, :edit, :new]
  load_and_authorize_resource

  def index
    @filter_dogs = ["name", "weight", "height"]
    @dogs = if params[:commit].present?
      Dog.search params[:search_dog], params[:search]
    else
      @dogs
    end
    @dogs = @dogs.page params[:page]
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
  end

  def create
    @dog = current_user.dogs.build dogs_params
    if @dog.save
      flash[:success] = t "dogs.created"
      redirect_to admin_dogs_path
    else
      load_categories
      render :new
    end
  end

  def edit
  end

  def show
    @review = Review.new
  end

  def update
    if @dog.update_attributes dogs_params
      flash[:success] = t "dogs.updated"
      redirect_to admin_dogs_path
    else
      load_categories
      render :edit
    end
  end

  def destroy
    if @dog.destroy
      flash[:success] = "Successfully deleted..."
    else
      flash[:danger] = "Not deleted..."
    end
    redirect_to admin_dogs_path
  end

  private
  def dogs_params
    params.require(:dog).permit :name, :weight, :height, :origin, :category_id,
      :description, :avg_life_expectancy, :image
  end

  def load_categories
    @categories = Category.all.collect {|category| [category.name, category.id]}
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  load_and_authorize_resource except: :index
  before_action :load_categories, only: [:index, :new, :edit]
  before_action :load_data, only: :show
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if params[:category_id]
      @dogs = Category.find_by(id: params[:category_id]).dogs.order(rate: :desc)
        .page params[:page]
      render "index.js.erb"
    else
      if params[:current_controller] == "dogs" && params[:current_action] == "index"
        @dogs = if params[:commit].present? && !params[:search].blank?
          Dog.search params[:search_dog], params[:search], params[:search_2]
        else
          Category.first.dogs
        end
        @dogs = @dogs.order(rate: :desc).page params[:page]
        respond_to do |format|
          format.html
          format.js
        end
      else
        @dogs = Dog.search params[:search_dog], params[:search], params[:search_2]
        @dogs = @dogs.order(rate: :desc).page params[:page]
        render template: "dogs/index.html"
      end
    end
  end

  def show
  end

  def new
  end

  def create
    @dog = current_user.dogs.build dogs_params
    if @dog.save
      flash[:success] = t "dogs.created"
      redirect_to dogs_path
    else
      load_categories
      render :new
    end
  end

  def edit
  end

  def update
    if @dog.update_attributes dogs_params
      flash[:success] = t "dogs.updated"
      redirect_to dogs_path
    else
      load_categories
      render :edit
    end
  end

  def destroy
    if @dog.destroy
      flash[:success] = "Successfully deleted..."
    else
      flash[:danger] = "Not deleted..."
    end
    redirect_to dogs_path
  end

  private
  def dogs_params
    params.require(:dog).permit :name, :weight, :height, :origin, :category_id,
      :description, :avg_life_expectancy, :image
  end

  def load_categories
    @categories = Category.all.collect {|a| [a.name, a.id]}
  end

  def load_data
    @dog = Dog.includes(:reviews).find_by id: params[:id]
    @review = Review.new
  end
end

app/views/dogs/_condition_fields.html.erb
<div class="field user-field">
  <div class="col-md-3 height">
    <%= f.attribute_fields do |a| %>
      <%= a.attribute_select %>
    <% end %>
  </div>
  <div class="col-md-3 height">
    <%= f.predicate_select %>
  </div>
  <div class="col-md-3 height">
    <%= f.value_fields do |v| %>
      <%= v.text_field :value, class: "form-control" %>
    <% end %>
  </div>
  <div class="col-md-3 height">
    <%= c.submit t("users.search"), class: "btn btn-success" %>
    <%= link_to t("dogs.remove"), "#",
      class: "remove_fields btn btn-danger" %>
  </div>
</div>

app/views/dogs/_dog.html.erb
<div class="col-md-4" style="height: 420px;">
  <%= link_to dog do %>
    <div class="dog-view">
      <div class="image-dog text-center">
        <%= set_image_dog dog %>
      </div>
      <% if user_signed_in? && controller_name != "users" %>
        <div id="favorite-<%= dog.id %>">
          <% if check_favorite dog %>
            <%= controller_name == dog ? render("unfavorite", dog: dog) :
              render("dogs/unfavorite", dog: dog) %>
          <% else %>
            <%= render "favorite", dog: dog %>
          <% end %>
        </div>
      <% end %>
      <h2><%= dog.name %></h2>
      <div class="content-dog">
        <div class="rate"></div>
        <div class="row">
          <div class="col-md-6 col-xs-6">
            <b><%= t "dogs.weight" %>: </b>
            <%= dog.weight %>
            <%= t "dogs.kg" %>
          </div>
          <div class="col-md-6 col-xs-6">
            <span class="pull-right">
              <b><%= t "dogs.height" %>: </b>
              <%= dog.height %>
              <%= t "dogs.cm" %>
            </span>
          </div>
        </div>
        <div class="row">
          <div class="col-md-8 col-xs-8">
            <b><%= t "dogs.avg_life_expectancy" %>: </b>
          </div>
          <div class="col-md-4 col-xs-4">
            <span class="pull-right">
              <%= dog.avg_life_expectancy %>
              <%= t "dogs.year" %>
            </span>
          </div>
          <div style="display: inline-flex; margin-left: 30%;">
            <% if dog.rate %>
              <label>Rate</label>: <span class="rating-static
                star-<%= dog.rate * 10 %>"></span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="text-center compare-<%= dog.id %>">
      <%= link_to "Add Compare", new_compare_path(dog_id: dog.id), remote: true %>
    </div>
  <% end %>
</div>

app/views/dogs/_favorite.html.erb
<div class="favorite">
  <%= link_to favorites_path(dog_id: dog.id), remote: true, method: :post do %>
    <i class="glyphicon glyphicon-heart star star-favorite"></i>
  <% end %>
</div>

app/views/dogs/_form.html.erb
<div class="form-dog">
  <%= form_for @dog do |f| %>
    <%= render "shared/error_messages", object: @dog %>
    <div class="form-group">
    <%= f.label :category %>
      <%= f.select :category_id, options_for_select(@categories), {},
        {selected: f.object.category_id,class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :origin %>
      <%= f.text_field :origin, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.file_field :image %>
    </div>
    <div class="row">
      <div class="col-md-4 col-xs-4">
        <div class="form-group">
          <%= f.label :weight %>
          <%= f.number_field :weight, min: 0, step: 1, class: "form-control",
            placeholder: t("dogs.please_input_weight") %>
        </div>
      </div>
      <div class="col-md-4 col-xs-4">
        <div class="form-group">
          <%= f.label :height %>
          <%= f.number_field :height, min: 0, step: 1, class: "form-control",
            placeholder: t("dogs.please_input_height") %>
        </div>
      </div>
      <div class="col-md-4 col-xs-4">
        <div class="form-group">
          <%= f.label :avg_life_expectancy %>
          <%= f.number_field :avg_life_expectancy, min: 0, step: 1,
            class: "form-control", placeholder: t("dogs.please_input_height") %>
        </div>
      </div>
      <%= f.submit t("button.#{params[:action]}"),
        class: "btn btn-primary pull-right" %>
    </div>
  <% end %>
</div>

app/views/dogs/_form_review.html.erb
<%= form_for @review do |f| %>
  <%= render "shared/error_messages", object: @review %>
  <div class="form-group">
    <div><%= f.label :rate_this_dog %></div>
    <div class="text-left">
      <span class="glyphicon glyphicon-star star" id="rate-1"></span>
      <span class="glyphicon glyphicon-star star" id="rate-2"></span>
      <span class="glyphicon glyphicon-star star" id="rate-3"></span>
      <span class="glyphicon glyphicon-star star" id="rate-4"></span>
      <span class="glyphicon glyphicon-star star" id="rate-5"></span>
    </div>
    <%= f.hidden_field :rate, value: @review.rate %>
  </div>
  <div class="form-group">
    <div><%= f.label :content %></div>
    <%= f.text_area :content, placeholder: t("reviews.content"),
      class: "form-control height-text-area" %>
  </div>
  <%= f.hidden_field :targetable_id, value: @dog.id %>
  <%= f.hidden_field :targetable_type, value: Dog.name %>
  <%= f.hidden_field :user_id, value: current_user.id if current_user %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/dogs/_unfavorite.html.erb
<div class="unfavorite">
  <%= link_to check_favorite(dog), remote: true, method: :delete do %>
    <i class="glyphicon glyphicon-heart star star-favorite"></i>
  <% end %>
</div>

app/views/dogs/edit.html.erb
<% provide :title, t("dogs.edit") %>
<div id="dogs">
  <div class="col-md-8 col-md-offset-2 edit-dog">
    <%= render "form" %>
  </div>
</div>

app/views/dogs/index.html.erb
<% provide :title, t("dogs.title") %>
<div id="dogs">
  <div class="row a-dog">
    <div class="col-md-2 col-xs-2">
      <h3><%= link_to t("categories.new"), new_dog_path,
        class: "btn btn-success" %></h3>
      <h3><%= link_to "Favorites", favorites_path if user_signed_in? %></h3>
      <label>Select Categories</label>
      <div style="max-height: 200px; overflow: auto">
        <% Category.all.each do |category| %>
          <div class="check-box-category" title="<%= category.name %>">
            <label>
              <%= radio_button_tag :category_id, category.id %>
              <%= category.name %>
            </label>
          </div>
        <% end %>
      </div>
      <hr>
      <b>Event</b>
      <div style="max-height: 200px; overflow: auto">
        <% Event.all.each do |event| %>
          <div>
            <%= link_to event.name, events_path(event: event.id),
              class: "event-index-dog", title: event.name %>
          </div>
        <% end %>
      </div>
      <div class="compare"></div>
      <div class="compare_now" hidden>
        <%= link_to "Compare Now", "" %>
      </div>
    </div>
    <div class="col-md-10 col-xs-10">
      <div class="all-dog row">
        <%= render @dogs if @dogs %>
      </div>
    </div>
  </div>
  <div class="text-center"><%= paginate @dogs %></div>
</div>

app/views/dogs/new.html.erb
<% provide :title, t("dogs.new") %>
<div id="dogs">
  <div class="col-md-8 col-md-offset-2 new-dog">
    <%= render "form" %>
  </div>
</div>

app/views/dogs/show.html.erb
<% provide :title, @dog.name %>
<div id="dogs">
  <div class="show-dog row">
    <div class="col-md-10 col-md-offset-1">
      <div class="row">
        <div class="col-md-4">
          <div class="dog-view">
            <div class="image-dog text-center">
              <%= set_image_dog @dog %>
            </div>
            <h2><%= @dog.name %></h2>
            <div class="content-dog">
              <div class="rate"></div>
              <div class="row">
                <div class="col-md-6 col-xs-6 center">
                  <b><%= t "dogs.weight" %>: </b>
                  <%= @dog.weight %>
                  <%= t "dogs.kg" %>
                </div>
                <div class="col-md-6 col-xs-6">
                  <b><%= t "dogs.height" %>: </b>
                  <%= @dog.height %>
                  <%= t "dogs.cm" %>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6 col-xs-6">
                  <b class="pull-right"><%= t "dogs.avg_life_expectancy" %>: </b>
                </div>
                <div class="col-md-6 col-xs-6">
                  <span class="pull-left">
                    <%= @dog.avg_life_expectancy %>
                    <%= t "dogs.year" %>
                  </span>
                </div>

                <div style="display: inline-flex; margin-left: 30%;">
                  <% if @dog.rate %>
                    <label>Rate</label>: <span class="rating-static
                      star-<%= @dog.rate * 10 %>"></span>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-7 col-md-offset-1">
          <div class="dog-content">
            <p><b><%= t "dogs.name" %>: </b><%= @dog.name %></p>
            <p><b><%= t "dogs.origin" %>: </b><%= @dog.origin %></p>
            <p><b><%= t "dogs.description" %>: </b><%= @dog.description %></p>
            <%= link_to "View all dog", dogs_path, class: "btn btn-info" %>
            <%= link_to "Write a reviews", "#review_content",
              class: "btn btn-primary" %>
            <%= link_to "Edit",edit_dog_path(@dog) if
              current_user?(@dog.user) %>
            <%= link_to t("users.delete"), @dog, method: :delete, class: "color-red",
              data: {confirm: t("delete.confirm", name: @dog.name)} if
              current_user?(@dog.user) %>
          </div>
          <br>
          <div>
            <%= render @dog.reviews.order created_at: :desc %>
          </div>
          <hr>
          <div class="form-review">
            <%= render "form_review" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>