config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "auth", path_names: {sign_in: "login",
    sign_out: "logout"},
    controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  namespace :admin do
    root "dogs#index"
    resources :categories
    resources :users
    resources :dogs
    resources :reviews
  end
  root "dogs#index"
  resources :users
  resources :dogs
  resources :reviews
  resources :favorites, only: [:create, :destroy, :index]
  resources :compares
  resources :events
  resources :user_events
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  devise :database_authenticatable, :registerable, :rememberable, :validatable,
    :omniauthable, :recoverable

  has_many :reviews, dependent: :destroy
  has_many :dogs, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :user_events, dependent: :destroy
  has_many :events, through: :user_events

  class << self
    def from_omniauth auth
      find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
        user.email = auth.info.email
        user.password = "12345678"
        user.name = auth.info.name
      end
    end

    def new_with_session params, session
      super.tap do |user|
        if data = session["devise.facebook_data"] &&
          session["devise.facebook_data"]["extra"]["raw_info"]
          user.email = data["email"] if user.email.blank?
        end
      end
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!

  def index
  end

  def show
  end

  def destroy
    if @user.destroy
      flash[:success] = t "users.deleted"
    else
      flash[:danger] = t "users.delete_fail"
    end
    redirect_to admin_users_path
  end

  private
  def user_params
    params.require(:user).permit :email, :name, :avatar
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth request.env["omniauth.auth"]
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      if is_navigational_format?
        set_flash_message :notice, :success, kind: "Facebook"
      end
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, except: [:index, :show]

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = "Successfully updated..."
    else
      flash[:danger] = "Not updated..."
    end
    redirect_to :back
  end
  private
  def user_params
    params.require(:user).permit :email, :name, :avatar
  end
end

app/views/users/_event.html.erb
<div id="event-<%= event.id %>" class="event"
  style="list-style: none; margin-bottom: 5px;">
  <div class="row">
    <div class="col-md-4">
      <%= link_to event.name, events_path(event: event.id) %>
    </div>
    <div class="col-md-4">
      <%= load_user_event(event).status if load_user_event event %>
    </div>
    <div class="col-md-4">
      <%= link_to "Edit", edit_event_path(event), class: "btn btn-xs btn-primary" if
        current_user?(event.user) %>
      <%= link_to "Delete", event_path(event), method: :delete,
        data: {confirm: "Arey you sure? "}, class: "btn btn-xs btn-danger" if
        current_user?(event.user) %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% provide :title, t("users.edit") %>
<h1><%= t "users.edit" %></h1>
<div class="col-md-6 col-md-offset-3">
  <%= form_for @user do |f| %>
    <%= render "shared/error_messages", object: @user %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, autofocus: true, class: "form-control" %>
    </div>

    <div class="field">
      <%= f.label :email %>
      <%= f.email_field :email, autofocus: true, class: "form-control" %>
    </div>

    <div class="input">
      <%= f.label :avatar %>
      <%= f.file_field :avatar %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <i><%= t "users.leave_blank" %></i>
      <% if @minimum_password_length %>
        <em><%= t "devise.registrations.minimum_password_length",
          minpasslength: @minimum_password_length %></em>
      <% end %>
      <%= f.password_field :password, autocomplete: "off",
        class: "form-control" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, autocomplete: "off",
        class: "form-control" %>
    </div>

    <div class="field">
      <%= f.label :current_password %>
      <i>
        <%= t "users.need_current_pass" %><br>
        <%= t "users.default_password" if @user.uid.present? %>
      </i>
      <%= f.password_field :current_password, autocomplete: "off",
        class: "form-control" %>
    </div>

    <div class="actions center">
      <%= f.submit t("users.save"),
        class: "btn btn-primary" %>
    </div>
  <% end %>
  <p class="center">
    <%= link_to t("back"), :back, class: "btn btn-info back" %>
  </p>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div id="users" style="margin-top: 30px;">
  <div class="row">
    <div class="event list-event col-md-8 col-md-offset-2">
      <div class="row header">
        <div class="col-md-4"><b>Events</b></div>
        <div class="col-md-4"><b>Status</b></div>
        <div class="col-md-4"><b>Action</b></div>
      </div>
      <% Event.event_of_user(current_user.id).each do |event| %>
        <%= render "event", event: event %>
      <% end %>
    </div>
  </div>
  <hr>
  <div class="row table table-striped text-center">
    <div class="col-sm-4 col-xs-4">
      <%= @user.name %>
    </div>
    <div class="col-sm-4 col-xs-4">
      <%= @user.email %>
    </div>
    <div class="col-sm-4 col-xs-4">
      <%= @user.dogs.any? ? @user.dogs.size : 0 %>
      <%= t "users.image" %>
    </div>
  </div>
  <hr />
  <%= render @user.dogs %>
</div>