config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "auth", path_names: {sign_in: "login",
    sign_out: "logout"},
    controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  namespace :admin do
    root "dogs#index"
    resources :categories
    resources :users
    resources :dogs
    resources :reviews
  end
  root "dogs#index"
  resources :users
  resources :dogs
  resources :reviews
  resources :favorites, only: [:create, :destroy, :index]
  resources :compares
  resources :events
  resources :user_events
end

app/models/event.rb
class Event < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :user_events, dependent: :destroy
  has_many :users, through: :user_events
  has_many :reviews, dependent: :destroy, as: :targetable

  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :name, presence: true
  validate :check_time

  scope :event_of_user, ->user_id{joins(:user_events)
    .where("(user_events.user_id = ? AND user_events.status =
    #{UserEvent.statuses[:participation]}) OR events.user_id = ?", user_id, user_id).distinct}

  private
  def check_time
    if start_time && end_time && start_time > end_time
      errors.add :end_time, "cannot left than start time"
    elsif start_time && start_time < Time.zone.now
      errors.add :start_time, "cannot left than time now"
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource

  def index
    @review = Review.new
    if params[:event_id] && @events.any?
      @event = Event.find_by id: params[:event_id]
      render "index.js.erb"
    elsif params[:event] && @events.any?
      @event = Event.find_by id: params[:event]
    else
      @event = @events.first
    end
  end

  def new
  end

  def create
    if @event.save
      UserEvent.create user: current_user, event: @event, status: 0
      flash[:success] = t "events.created"
      redirect_to events_path
    else
      flash[:danger] = t "events.not_created"
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update_attributes event_params
      flash[:success] = t "events.updated"
      redirect_to events_path
    else
      flash[:danger] = t "events.not_updated"
      render :edit
    end
  end

  def destroy
    if @event.destroy
      flash[:success] = t "events.deleted"
    else
      flash[:danger] = t "events.not_deleted"
    end
    redirect_to :back
  end

  private
  def event_params
    params.require(:event).permit :name, :start_time, :location, :description,
      :user_id, :end_time, :image
  end
end

app/views/events/_event.html.erb
<div data-id="<%= event.id %>" class="event" id="event-<%= event.id %>">
  <%= event.name %>
  <ul class="list-status hidden text-left">
    <% if load_user_event event %>
      <% UserEvent.statuses.each do |key, value| %>
        <li style="list-style: none; margin-left: 30%;">
          <%= link_to key, user_event_path(load_user_event(event), status: key),
            data: {method: :patch, confirm: "Are you sure?"},
            class: "btn #{key} btn-xs action-user-event" %>
        </li>
      <% end %>
    <% else %>
      <% UserEvent.statuses.each do |key, value| %>
        <li style="list-style: none; margin-left: 30%;">
          <%= link_to key, user_events_path(event_id: event.id, status: key),
            data: {method: :post, confirm: "Are you sure?"},
            class: "btn #{key} btn-xs action-user-event" %>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/events/_event_info.html.erb
<div class="text-center">
  <b>Owner: </b><%= @event.user.name %>
</div>
<div class="row event-info">
  <div class="col-md-12 text-center"><%= set_image_event @event %></div>
  <div class="col-md-4">
    <b>Start Time: </b><%= @event.start_time %>
  </div>
  <div class="col-md-4">
    <b>End Time: </b><%= @event.start_time %>
  </div>
  <div class="col-md-12">
    <b>Location: </b><%= @event.location %>
  </div>
  <div class="col-md-12">
    <b>Description: </b><%= @event.description %>
  </div>
  <% if load_user_event(@event) %>
    <div class="col-md-12">
      <b>You: </b><%= load_user_event(@event).status %>
    </div>
    <div class="col-md-12">
      <%= social_share_button_tag(@event.name) %>
    </div>
  <% end %>
</div>
<hr>
<div class="list-review">
  <%= render @event.reviews.order created_at: :desc %>
</div>
<div class="form-review">
  <%= render "form_review" %>
</div>

app/views/events/_form.html.erb
<div class="form-event" style="margin-top: 30px;">
  <%= form_for @event do |f| %>
    <%= render "shared/error_messages", object: @event %>
    <div class="form-group">
      <%= f.label :name_event %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.file_field :image %>
    </div>
    <div class="form-group">
      <%= f.label :start_time %>
      <%= f.text_field :start_time, class: "form-control datepicker" %>
    </div>
    <div class="form-group">
      <%= f.label :end_time %>
      <%= f.text_field :end_time, class: "form-control datepicker" %>
    </div>
    <div class="form-group">
      <%= f.label :location %>
      <%= f.text_field :location, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control" %>
    </div>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit (@event.new_record? ? "Create" : "Update"),
      class: "btn btn-success pull-right" %>
  <% end %>
</div>

app/views/events/_form_review.html.erb
<%= form_for @review, remote: true do |f| %>
  <%= render "shared/error_messages", object: @review %>
  <div class="form-group">
    <div><%= f.label :content %></div>
    <%= f.text_area :content, placeholder: "Please Input Comment",
      class: "form-control height-text-area" %>
  </div>
  <%= f.hidden_field :targetable_id, value: @event.id %>
  <%= f.hidden_field :targetable_type, value: Event.name %>
  <%= f.hidden_field :rate, value: 0 %>
  <%= f.hidden_field :user_id, value: current_user.id if current_user %>
  <%= f.submit "Comment", class: "btn btn-primary" %>
<% end %>

app/views/events/edit.html.erb
<% provide :title, "Edit" %>
<div id="events">
  <div class="col-md-8 col-md-offset-2 edit-event">
    <%= render "form" %>
  </div>
</div>

app/views/events/index.html.erb
<div id="events">
  <div class="col-md-4">
    <div class="text-center">
      <h2>List Events</h2>
      <div class="text-center">
        <%= link_to "New Event", new_event_path, class: "btn btn-sm btn-success" %>
      </div><hr>
      <%= render @events %>
    </div>
  </div>
  <div class="col-md-8">
    <div class="event-info">
      <%= render "event_info" if @event %>
    </div>
  </div>
</div>

app/views/events/index.js.erb
$('.event-info').html("<%= j render "event_info" if @event %>");

app/views/events/new.html.erb
<% provide :title, t("dogs.new") %>
<div id="events">
  <div class="col-md-8 col-md-offset-2 new-event">
    <%= render "form" %>
  </div>
</div>