config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "auth", path_names: {sign_in: "login",
    sign_out: "logout"},
    controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  namespace :admin do
    root "dogs#index"
    resources :categories
    resources :users
    resources :dogs
    resources :reviews
  end
  root "dogs#index"
  resources :users
  resources :dogs
  resources :reviews
  resources :favorites, only: [:create, :destroy, :index]
  resources :compares
  resources :events
  resources :user_events
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :dogs, dependent: :destroy
  validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!

  def index
    @categories = @categories.includes(:dogs) if @categories
  end

  def new
  end

  def create
    if @category.save
      flash[:success] = t "categories.created"
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def edit
  end

  def show
  end

  def update
    if @category.update_attributes categories_params
      flash[:success] = t "categories.updated"
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t "categories.deleted"
    else
      flash[:danger] = t "categories.not_delete"
    end
    redirect_to admin_categories_path
  end

  private
  def categories_params
    params.require(:category).permit :name
  end
end

app/views/admin/categories/_category.html.erb
<tr>
  <td><%= link_to category.name, [:admin, category] %></td>
  <td><%= category.dogs.any? ? category.dogs.size : 0 %></td>
  <td><%= link_to t("categories.edit"), edit_admin_category_path(category) %></td>
</tr>

app/views/admin/categories/_dog.html.erb
<%= link_to admin_dog_path(dog) do %>
  <div class="col-md-4">
    <div class="dog-view">
      <div class="image-dog">
        <%= set_image_dog dog %>
      </div>
      <h2><%= dog.name %></h2>
      <div class="content-dog">
        <div class="rate"></div>
        <div class="row">
          <div class="col-md-6 col-xs-6">
            <b><%= t "dogs.weight" %>: </b>
            <%= dog.weight %>
            <%= t "dogs.kg" %>
          </div>
          <div class="col-md-6 col-xs-6">
            <span class="pull-right">
              <b><%= t "dogs.height" %>: </b>
              <%= dog.height %>
              <%= t "dogs.cm" %>
            </span>
          </div>
        </div>
        <div class="row">
          <div class="col-md-8 col-xs-8">
            <b><%= t "dogs.avg_life_expectancy" %></b>
          </div>
          <div class="col-md-4 col-xs-4">
            <span class="pull-right">
              <%= dog.avg_life_expectancy %>
              <%= t "dogs.year" %>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/categories/_form.html.erb
<div class="form-category">
  <%= form_for [:admin, @category] do |f| %>
    <%= render "shared/error_messages", object: @category %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
      <%= f.submit t("button.#{params[:action]}"),
        class: "btn btn-primary pull-right" %>
    </div>
  <% end %>
</div>

app/views/admin/categories/edit.html.erb
<% provide :title, t("categories.new") %>
<div id="categories">
  <div class="col-md-8 col-md-offset-2 new-category">
    <%= render "form" %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<% provide :title, t("categories.title") %>
<div id="categories">
  <div class="row a-dog">
    <div class="col-md-10 col-md-offset-1">
    <h3><%= link_to t("categories.new"), new_admin_category_path,
      class: "btn btn-success" %></h2>
      <table class="table table-hover table-striped row">
        <thead>
          <tr>
            <th class="col-sm-4 col-xs-4"><%= t "categories.name" %></th>
            <th class="col-sm-4 col-xs-4"><%= t "categories.image_total" %></th>
            <th class="col-sm-4 col-xs-4"></th>
          </tr>
        </thead>
        <tbody>
          <%= render @categories if @categories %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/categories/new.html.erb
<% provide :title, t("categories.new") %>
<div id="categories">
  <div class="col-md-8 col-md-offset-2 new-category">
    <%= render "form" %>
  </div>
</div>

app/views/admin/categories/show.html.erb
<% provide :title, @category.name %>
<div id="categorys">
  <div class="row table table-striped text-center">
    <div class="col-sm-4 col-xs-4">
      <%= @category.name %>
    </div>
    <div class="col-sm-4 col-xs-4">
      <%= @category.dogs.any? ? @category.dogs.size : 0 %>
      <%= t "categorys.image" %>
    </div>
    <div class="col-sm-4 col-xs-4">
      <%= link_to t("categorys.delete"), admin_category_path(@category), method: :delete,
        data: {confirm: t("delete.confirm", name: @category.name)},
        class: "btn btn-danger" %>
    </div>
  </div>
  <hr />
  <%= render @category.dogs %>
</div>